VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ITestResultReporter"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'---------------------------------------------------------------------------------------
' Interface: ITestResultReporter
'---------------------------------------------------------------------------------------
'
' Interface for Reporter classes
'
'---------------------------------------------------------------------------------------
Option Compare Text
Option Explicit

Public Property Set TestResultCollector(ByVal NewValue As TestResultCollector)
'
End Property
