//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessCodeLib.AccUnit.VbeAddIn.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserControls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserControls() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccessCodeLib.AccUnit.VbeAddIn.Resources.UserControls", typeof(UserControls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string InputBoxButtonCancelCaption {
            get {
                return ResourceManager.GetString("InputBoxButtonCancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string InputBoxButtonOkCaption {
            get {
                return ResourceManager.GetString("InputBoxButtonOkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert new test method ähnelt.
        /// </summary>
        internal static string InsertTestMethodUserControlInfoCaption {
            get {
                return ResourceManager.GetString("InsertTestMethodUserControlInfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New class name: ähnelt.
        /// </summary>
        internal static string InsertTestTemplateInputboxPromptText {
            get {
                return ResourceManager.GetString("InsertTestTemplateInputboxPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Test ähnelt.
        /// </summary>
        internal static string InsertTestTemplateInputboxTitle {
            get {
                return ResourceManager.GetString("InsertTestTemplateInputboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove AccUnit test environment ähnelt.
        /// </summary>
        internal static string RemoveEnvironmentMessageBoxCaption {
            get {
                return ResourceManager.GetString("RemoveEnvironmentMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - Export and remove all tests
        ///- remove references (AccUnit, SimplyVBUnit)
        ///
        ///Remove environment? ähnelt.
        /// </summary>
        internal static string RemoveEnvironmentMessageBoxText {
            get {
                return ResourceManager.GetString("RemoveEnvironmentMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Commit ähnelt.
        /// </summary>
        internal static string SelectListCommitButtonText {
            get {
                return ResourceManager.GetString("SelectListCommitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select All ähnelt.
        /// </summary>
        internal static string SelectListSelectAllCheckboxCaption {
            get {
                return ResourceManager.GetString("SelectListSelectAllCheckboxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die use filter ähnelt.
        /// </summary>
        internal static string TagListUserControlCommitButtonText {
            get {
                return ResourceManager.GetString("TagListUserControlCommitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AccUnit Tag List ähnelt.
        /// </summary>
        internal static string TagListUserControlInfoCaption {
            get {
                return ResourceManager.GetString("TagListUserControlInfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export Tests ähnelt.
        /// </summary>
        internal static string TestClassSelectionFormCaptionExport {
            get {
                return ResourceManager.GetString("TestClassSelectionFormCaptionExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import Tests ähnelt.
        /// </summary>
        internal static string TestClassSelectionFormCaptionImport {
            get {
                return ResourceManager.GetString("TestClassSelectionFormCaptionImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export ähnelt.
        /// </summary>
        internal static string TestClassSelectionFormCommitTestExport {
            get {
                return ResourceManager.GetString("TestClassSelectionFormCommitTestExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export &amp; Remove ähnelt.
        /// </summary>
        internal static string TestClassSelectionFormCommitTestExportAndRemove {
            get {
                return ResourceManager.GetString("TestClassSelectionFormCommitTestExportAndRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        internal static string TestClassSelectionFormCommitTestImport {
            get {
                return ResourceManager.GetString("TestClassSelectionFormCommitTestImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Tests ähnelt.
        /// </summary>
        internal static string TestClassSelectionFormOptionalCheckBoxTextExport {
            get {
                return ResourceManager.GetString("TestClassSelectionFormOptionalCheckBoxTextExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Run Tests ähnelt.
        /// </summary>
        internal static string TestExplorerCommitButtonText {
            get {
                return ResourceManager.GetString("TestExplorerCommitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AccUnit Test List ähnelt.
        /// </summary>
        internal static string TestListUserControlInfoCaption {
            get {
                return ResourceManager.GetString("TestListUserControlInfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message ähnelt.
        /// </summary>
        internal static string TestResultTreeListViewHeaderMessage {
            get {
                return ResourceManager.GetString("TestResultTreeListViewHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string TestResultTreeListViewHeaderName {
            get {
                return ResourceManager.GetString("TestResultTreeListViewHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AccUnit Test List ähnelt.
        /// </summary>
        internal static string TestResultUserControlInfoCaption {
            get {
                return ResourceManager.GetString("TestResultUserControlInfoCaption", resourceCulture);
            }
        }
    }
}
