//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessCodeLib.AccUnit.VbeAddIn.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserControls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserControls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccessCodeLib.AccUnit.VbeAddIn.Resources.UserControls", typeof(UserControls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string InputBoxButtonCancelCaption {
            get {
                return ResourceManager.GetString("InputBoxButtonCancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string InputBoxButtonOkCaption {
            get {
                return ResourceManager.GetString("InputBoxButtonOkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string InsertTestMethodCancelButtonText {
            get {
                return ResourceManager.GetString("InsertTestMethodCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        internal static string InsertTestMethodCommitButtonText {
            get {
                return ResourceManager.GetString("InsertTestMethodCommitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected behaviour.
        /// </summary>
        internal static string InsertTestMethodExpectedLabelCaption {
            get {
                return ResourceManager.GetString("InsertTestMethodExpectedLabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method under test.
        /// </summary>
        internal static string InsertTestMethodMethodNameLabelCaption {
            get {
                return ResourceManager.GetString("InsertTestMethodMethodNameLabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module to test.
        /// </summary>
        internal static string InsertTestMethodsCodeModuleToTestLabelCaption {
            get {
                return ResourceManager.GetString("InsertTestMethodsCodeModuleToTestLabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can insert tests for members of the selected module.
        ///Please select the members for which tests should be created..
        /// </summary>
        internal static string InsertTestMethodsSelectedModuleInstruction {
            get {
                return ResourceManager.GetString("InsertTestMethodsSelectedModuleInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select members to test:.
        /// </summary>
        internal static string InsertTestMethodsSelectMemberCaption {
            get {
                return ResourceManager.GetString("InsertTestMethodsSelectMemberCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State under test.
        /// </summary>
        internal static string InsertTestMethodStateLabelCaption {
            get {
                return ResourceManager.GetString("InsertTestMethodStateLabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new test method.
        /// </summary>
        internal static string InsertTestMethodUserControlInfoCaption {
            get {
                return ResourceManager.GetString("InsertTestMethodUserControlInfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New class name:.
        /// </summary>
        internal static string InsertTestTemplateInputboxPromptText {
            get {
                return ResourceManager.GetString("InsertTestTemplateInputboxPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Test.
        /// </summary>
        internal static string InsertTestTemplateInputboxTitle {
            get {
                return ResourceManager.GetString("InsertTestTemplateInputboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove AccUnit test environment.
        /// </summary>
        internal static string RemoveEnvironmentMessageBoxCaption {
            get {
                return ResourceManager.GetString("RemoveEnvironmentMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Export and remove all tests
        ///- remove references (AccUnit, SimplyVBUnit)
        ///
        ///Remove environment?.
        /// </summary>
        internal static string RemoveEnvironmentMessageBoxText {
            get {
                return ResourceManager.GetString("RemoveEnvironmentMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        internal static string SelectListCommitButtonText {
            get {
                return ResourceManager.GetString("SelectListCommitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string SelectListSelectAllCheckboxCaption {
            get {
                return ResourceManager.GetString("SelectListSelectAllCheckboxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use filter.
        /// </summary>
        internal static string TagListUserControlCommitButtonText {
            get {
                return ResourceManager.GetString("TagListUserControlCommitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccUnit Tag List.
        /// </summary>
        internal static string TagListUserControlInfoCaption {
            get {
                return ResourceManager.GetString("TagListUserControlInfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Tests.
        /// </summary>
        internal static string TestClassSelectionFormCaptionExport {
            get {
                return ResourceManager.GetString("TestClassSelectionFormCaptionExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Tests.
        /// </summary>
        internal static string TestClassSelectionFormCaptionImport {
            get {
                return ResourceManager.GetString("TestClassSelectionFormCaptionImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export.
        /// </summary>
        internal static string TestClassSelectionFormCommitTestExport {
            get {
                return ResourceManager.GetString("TestClassSelectionFormCommitTestExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export &amp; Remove.
        /// </summary>
        internal static string TestClassSelectionFormCommitTestExportAndRemove {
            get {
                return ResourceManager.GetString("TestClassSelectionFormCommitTestExportAndRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import.
        /// </summary>
        internal static string TestClassSelectionFormCommitTestImport {
            get {
                return ResourceManager.GetString("TestClassSelectionFormCommitTestImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Tests.
        /// </summary>
        internal static string TestClassSelectionFormOptionalCheckBoxTextExport {
            get {
                return ResourceManager.GetString("TestClassSelectionFormOptionalCheckBoxTextExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Run Tests.
        /// </summary>
        internal static string TestExplorerCommitButtonText {
            get {
                return ResourceManager.GetString("TestExplorerCommitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccUnit Test List.
        /// </summary>
        internal static string TestListUserControlInfoCaption {
            get {
                return ResourceManager.GetString("TestListUserControlInfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string TestResultTreeListViewHeaderMessage {
            get {
                return ResourceManager.GetString("TestResultTreeListViewHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TestResultTreeListViewHeaderName {
            get {
                return ResourceManager.GetString("TestResultTreeListViewHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccUnit Test List.
        /// </summary>
        internal static string TestResultUserControlInfoCaption {
            get {
                return ResourceManager.GetString("TestResultUserControlInfoCaption", resourceCulture);
            }
        }
    }
}
