//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessCodeLib.AccUnit.VbeAddIn.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VbeCommandbars {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VbeCommandbars() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccessCodeLib.AccUnit.VbeAddIn.Resources.VbeCommandbars", typeof(VbeCommandbars).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert Test Method ähnelt.
        /// </summary>
        internal static string InsertTestMethodCommandbarButtonCaption {
            get {
                return ResourceManager.GetString("InsertTestMethodCommandbarButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run &amp;all tests ähnelt.
        /// </summary>
        internal static string RunAllTestsCommandBarButtonCaption {
            get {
                return ResourceManager.GetString("RunAllTestsCommandBarButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run all tests of current VBProject ähnelt.
        /// </summary>
        internal static string RunAllTestsCommandBarButtonDescription {
            get {
                return ResourceManager.GetString("RunAllTestsCommandBarButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run current &amp;test ähnelt.
        /// </summary>
        internal static string RunCurrentTestCommandBarButtonCaption {
            get {
                return ResourceManager.GetString("RunCurrentTestCommandBarButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run current test (visible in VBA editor) ähnelt.
        /// </summary>
        internal static string RunCurrentTestCommandBarButtonDescription {
            get {
                return ResourceManager.GetString("RunCurrentTestCommandBarButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select tags ähnelt.
        /// </summary>
        internal static string SelectTagsCommandBarButtonCaption {
            get {
                return ResourceManager.GetString("SelectTagsCommandBarButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select tags and run tests ähnelt.
        /// </summary>
        internal static string SelectTagsCommandBarButtonDescription {
            get {
                return ResourceManager.GetString("SelectTagsCommandBarButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select tests ähnelt.
        /// </summary>
        internal static string SelectTestsCommandBarButtonCaption {
            get {
                return ResourceManager.GetString("SelectTestsCommandBarButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select and run tests  ähnelt.
        /// </summary>
        internal static string SelectTestsCommandBarButtonDescription {
            get {
                return ResourceManager.GetString("SelectTestsCommandBarButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A&amp;bout ähnelt.
        /// </summary>
        internal static string ToolsAboutCommandbarButtonCaption {
            get {
                return ResourceManager.GetString("ToolsAboutCommandbarButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Acc&amp;Spec... ähnelt.
        /// </summary>
        internal static string ToolsAccSpecSpikeMenuItemCommandbarButtonCaption {
            get {
                return ResourceManager.GetString("ToolsAccSpecSpikeMenuItemCommandbarButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Acc&amp;Unit ähnelt.
        /// </summary>
        internal static string ToolsAccUnitSubMenuCaption {
            get {
                return ResourceManager.GetString("ToolsAccUnitSubMenuCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;New Test ähnelt.
        /// </summary>
        internal static string ToolsAccUnitTemplateSubMenuCaption {
            get {
                return ResourceManager.GetString("ToolsAccUnitTemplateSubMenuCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Export Tests... ähnelt.
        /// </summary>
        internal static string ToolsExportTestsCommandButtonCaption {
            get {
                return ResourceManager.GetString("ToolsExportTestsCommandButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Import Tests... ähnelt.
        /// </summary>
        internal static string ToolsImportTestsCommandButtonCaption {
            get {
                return ResourceManager.GetString("ToolsImportTestsCommandButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove environment ähnelt.
        /// </summary>
        internal static string ToolsRemoveTestEnvironmentCommandButtonCaption {
            get {
                return ResourceManager.GetString("ToolsRemoveTestEnvironmentCommandButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set test environment ähnelt.
        /// </summary>
        internal static string ToolsSetTestEnvironmentCommandButtonCaption {
            get {
                return ResourceManager.GetString("ToolsSetTestEnvironmentCommandButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Options... ähnelt.
        /// </summary>
        internal static string ToolsUserSettingFormCommandbarButtonCaption {
            get {
                return ResourceManager.GetString("ToolsUserSettingFormCommandbarButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tag List ähnelt.
        /// </summary>
        internal static string ViewTagListCommandbarButtonCaption {
            get {
                return ResourceManager.GetString("ViewTagListCommandbarButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Test Explorer ähnelt.
        /// </summary>
        internal static string ViewTestExplorerCommandbarButtonCaption {
            get {
                return ResourceManager.GetString("ViewTestExplorerCommandbarButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test &amp;Results ähnelt.
        /// </summary>
        internal static string ViewTestResultCommandbarButtonCaption {
            get {
                return ResourceManager.GetString("ViewTestResultCommandbarButtonCaption", resourceCulture);
            }
        }
    }
}
