//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessCodeLib.AccUnit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccessCodeLib.AccUnit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Sub {MethodUnderTest}_{StateUnderTest}_{ExpectedBehaviour}({Params})
        ///	&apos; Arrange
        ///	Err.Raise vbObjectError, &quot;{MethodUnderTest}_{StateUnderTest}_{ExpectedBehaviour}&quot;, &quot;Test not implemented&quot;
        ///	Const Expected As Variant = &quot;expected value&quot;
        ///	Dim Actual As Variant
        ///	&apos; Act
        ///	Actual = &quot;actual value&quot;
        ///	&apos; Assert
        ///	Assert.That Actual, Iz.EqualTo(Expected)
        ///End Sub
        ///.
        /// </summary>
        internal static string DefaultTestMethodTemplate {
            get {
                return ResourceManager.GetString("DefaultTestMethodTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;--------------------------------------------------------------------
        ///&apos; Tests
        ///&apos;--------------------------------------------------------------------
        ///.
        /// </summary>
        internal static string DefaultTestsSectionHeader {
            get {
                return ResourceManager.GetString("DefaultTestsSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New class name:.
        /// </summary>
        internal static string InsertTestTemplateInputboxPromptText {
            get {
                return ResourceManager.GetString("InsertTestTemplateInputboxPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Test.
        /// </summary>
        internal static string InsertTestTemplateInputboxTitle {
            get {
                return ResourceManager.GetString("InsertTestTemplateInputboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no (more) VbMsgBoxResults  available..
        /// </summary>
        internal static string MissingTestMessageBoxResult {
            get {
                return ResourceManager.GetString("MissingTestMessageBoxResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option Compare Text
        ///Option Explicit
        ///
        ///&apos;AccUnit:TestClass
        ///
        ///.
        /// </summary>
        internal static string TestClassCommonHeader {
            get {
                return ResourceManager.GetString("TestClassCommonHeader", resourceCulture);
            }
        }
    }
}
