# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pr: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'AzureCI'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*AccessTestClientTests.dll
      !**\*VBIDETools.Tests.dll
      !**\obj\**
    testFiltercriteria: "Category!=AccessClientTests"

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $assemblyPath = "$(Build.SourcesDirectory)\source\AccUnit\bin\Release\AccUnit.dll"
      $versionInfo = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($assemblyPath)
      $version = $versionInfo.FileVersion
      $parts = $version.Split('.')
      $version = "$($parts[0]).$($parts[1]).$($parts[2])"
      Write-Host "Version: $version"
      $version | Out-File "$(Build.ArtifactStagingDirectory)\version.txt"
      Get-ChildItem -Path "$(Build.SourcesDirectory)\source\AccUnit\bin\Release"
      Compress-Archive -Path "$(Build.SourcesDirectory)\source\AccUnit\bin\Release\AccessCodeLib.*.dll" -DestinationPath "$(Build.ArtifactStagingDirectory)\AccUnit.$($version).bin.zip"
      Compress-Archive -Path "$(Build.SourcesDirectory)\source\AccUnit\bin\Release\AccessCodeLib.*.tlb" -DestinationPath "$(Build.ArtifactStagingDirectory)\AccUnit.$($version).bin.zip" -Update
  displayName: 'Read Version and create zip file'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
